package com.sz.yxy.springboottest2.model;

public class TRouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rouse.rid
     *
     * @mbggenerated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rouse.rname
     *
     * @mbggenerated
     */
    private String rname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rouse.rid
     *
     * @return the value of t_rouse.rid
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rouse.rid
     *
     * @param rid the value for t_rouse.rid
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rouse.rname
     *
     * @return the value of t_rouse.rname
     *
     * @mbggenerated
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rouse.rname
     *
     * @param rname the value for t_rouse.rname
     *
     * @mbggenerated
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }
}