package com.sz.zhiling.model;

public class ExamUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_user.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_user.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_user.upwd
     *
     * @mbggenerated
     */
    private String upwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_user.userid
     *
     * @return the value of exam_user.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_user.userid
     *
     * @param userid the value for exam_user.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_user.uname
     *
     * @return the value of exam_user.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_user.uname
     *
     * @param uname the value for exam_user.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_user.upwd
     *
     * @return the value of exam_user.upwd
     *
     * @mbggenerated
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_user.upwd
     *
     * @param upwd the value for exam_user.upwd
     *
     * @mbggenerated
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }
}