package com.sz.zhiling.model;

public class ExamItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.epaperid
     *
     * @mbggenerated
     */
    private Integer epaperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.escore
     *
     * @mbggenerated
     */
    private Integer escore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.etype
     *
     * @mbggenerated
     */
    private Integer etype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.edegree
     *
     * @mbggenerated
     */
    private Integer edegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ea
     *
     * @mbggenerated
     */
    private String ea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.eb
     *
     * @mbggenerated
     */
    private String eb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ec
     *
     * @mbggenerated
     */
    private String ec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ed
     *
     * @mbggenerated
     */
    private String ed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ee
     *
     * @mbggenerated
     */
    private String ee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ef
     *
     * @mbggenerated
     */
    private String ef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ekeys
     *
     * @mbggenerated
     */
    private String ekeys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_items.ehints
     *
     * @mbggenerated
     */
    private String ehints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.eid
     *
     * @return the value of exam_items.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.eid
     *
     * @param eid the value for exam_items.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ename
     *
     * @return the value of exam_items.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ename
     *
     * @param ename the value for exam_items.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.epaperid
     *
     * @return the value of exam_items.epaperid
     *
     * @mbggenerated
     */
    public Integer getEpaperid() {
        return epaperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.epaperid
     *
     * @param epaperid the value for exam_items.epaperid
     *
     * @mbggenerated
     */
    public void setEpaperid(Integer epaperid) {
        this.epaperid = epaperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.escore
     *
     * @return the value of exam_items.escore
     *
     * @mbggenerated
     */
    public Integer getEscore() {
        return escore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.escore
     *
     * @param escore the value for exam_items.escore
     *
     * @mbggenerated
     */
    public void setEscore(Integer escore) {
        this.escore = escore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.etype
     *
     * @return the value of exam_items.etype
     *
     * @mbggenerated
     */
    public Integer getEtype() {
        return etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.etype
     *
     * @param etype the value for exam_items.etype
     *
     * @mbggenerated
     */
    public void setEtype(Integer etype) {
        this.etype = etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.edegree
     *
     * @return the value of exam_items.edegree
     *
     * @mbggenerated
     */
    public Integer getEdegree() {
        return edegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.edegree
     *
     * @param edegree the value for exam_items.edegree
     *
     * @mbggenerated
     */
    public void setEdegree(Integer edegree) {
        this.edegree = edegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ea
     *
     * @return the value of exam_items.ea
     *
     * @mbggenerated
     */
    public String getEa() {
        return ea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ea
     *
     * @param ea the value for exam_items.ea
     *
     * @mbggenerated
     */
    public void setEa(String ea) {
        this.ea = ea == null ? null : ea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.eb
     *
     * @return the value of exam_items.eb
     *
     * @mbggenerated
     */
    public String getEb() {
        return eb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.eb
     *
     * @param eb the value for exam_items.eb
     *
     * @mbggenerated
     */
    public void setEb(String eb) {
        this.eb = eb == null ? null : eb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ec
     *
     * @return the value of exam_items.ec
     *
     * @mbggenerated
     */
    public String getEc() {
        return ec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ec
     *
     * @param ec the value for exam_items.ec
     *
     * @mbggenerated
     */
    public void setEc(String ec) {
        this.ec = ec == null ? null : ec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ed
     *
     * @return the value of exam_items.ed
     *
     * @mbggenerated
     */
    public String getEd() {
        return ed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ed
     *
     * @param ed the value for exam_items.ed
     *
     * @mbggenerated
     */
    public void setEd(String ed) {
        this.ed = ed == null ? null : ed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ee
     *
     * @return the value of exam_items.ee
     *
     * @mbggenerated
     */
    public String getEe() {
        return ee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ee
     *
     * @param ee the value for exam_items.ee
     *
     * @mbggenerated
     */
    public void setEe(String ee) {
        this.ee = ee == null ? null : ee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ef
     *
     * @return the value of exam_items.ef
     *
     * @mbggenerated
     */
    public String getEf() {
        return ef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ef
     *
     * @param ef the value for exam_items.ef
     *
     * @mbggenerated
     */
    public void setEf(String ef) {
        this.ef = ef == null ? null : ef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ekeys
     *
     * @return the value of exam_items.ekeys
     *
     * @mbggenerated
     */
    public String getEkeys() {
        return ekeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ekeys
     *
     * @param ekeys the value for exam_items.ekeys
     *
     * @mbggenerated
     */
    public void setEkeys(String ekeys) {
        this.ekeys = ekeys == null ? null : ekeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_items.ehints
     *
     * @return the value of exam_items.ehints
     *
     * @mbggenerated
     */
    public String getEhints() {
        return ehints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_items.ehints
     *
     * @param ehints the value for exam_items.ehints
     *
     * @mbggenerated
     */
    public void setEhints(String ehints) {
        this.ehints = ehints == null ? null : ehints.trim();
    }

    public ExamItems() {
    }

    public ExamItems(Integer eid, String ename, Integer epaperid, Integer escore, Integer etype, Integer edegree, String ea, String eb, String ec, String ed, String ee, String ef, String ekeys, String ehints) {
        this.eid = eid;
        this.ename = ename;
        this.epaperid = epaperid;
        this.escore = escore;
        this.etype = etype;
        this.edegree = edegree;
        this.ea = ea;
        this.eb = eb;
        this.ec = ec;
        this.ed = ed;
        this.ee = ee;
        this.ef = ef;
        this.ekeys = ekeys;
        this.ehints = ehints;
    }
}