package com.sz.zhiling.model;

import java.util.Date;

public class ExamPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.paperid
     *
     * @mbggenerated
     */
    private Integer paperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.papername
     *
     * @mbggenerated
     */
    private String papername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.papertype
     *
     * @mbggenerated
     */
    private String papertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_paper.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.paperid
     *
     * @return the value of exam_paper.paperid
     *
     * @mbggenerated
     */
    public Integer getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.paperid
     *
     * @param paperid the value for exam_paper.paperid
     *
     * @mbggenerated
     */
    public void setPaperid(Integer paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.papername
     *
     * @return the value of exam_paper.papername
     *
     * @mbggenerated
     */
    public String getPapername() {
        return papername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.papername
     *
     * @param papername the value for exam_paper.papername
     *
     * @mbggenerated
     */
    public void setPapername(String papername) {
        this.papername = papername == null ? null : papername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.papertype
     *
     * @return the value of exam_paper.papertype
     *
     * @mbggenerated
     */
    public String getPapertype() {
        return papertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.papertype
     *
     * @param papertype the value for exam_paper.papertype
     *
     * @mbggenerated
     */
    public void setPapertype(String papertype) {
        this.papertype = papertype == null ? null : papertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.method
     *
     * @return the value of exam_paper.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.method
     *
     * @param method the value for exam_paper.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.remarks
     *
     * @return the value of exam_paper.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.remarks
     *
     * @param remarks the value for exam_paper.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_paper.create_time
     *
     * @return the value of exam_paper.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_paper.create_time
     *
     * @param createTime the value for exam_paper.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}