package com.sz.zhiling.model;

public class ExamScore {
    public ExamScore() {
    }

    public ExamScore(Integer userid, Integer paperid, Integer score, Integer rights, Integer errors) {
        this.userid = userid;
        this.paperid = paperid;
        this.score = score;
        this.rights = rights;
        this.errors = errors;
    }

    public ExamScore(Integer scoreid, Integer userid, Integer paperid, Integer score, Integer rights, Integer errors) {
        this.scoreid = scoreid;
        this.userid = userid;
        this.paperid = paperid;
        this.score = score;
        this.rights = rights;
        this.errors = errors;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_score.scoreid
     *
     * @mbggenerated
     */


    private Integer scoreid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_score.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_score.paperid
     *
     * @mbggenerated
     */
    private Integer paperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_score.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_score.rights
     *
     * @mbggenerated
     */
    private Integer rights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_score.errors
     *
     * @mbggenerated
     */
    private Integer errors;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_score.scoreid
     *
     * @return the value of exam_score.scoreid
     *
     * @mbggenerated
     */
    public Integer getScoreid() {
        return scoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_score.scoreid
     *
     * @param scoreid the value for exam_score.scoreid
     *
     * @mbggenerated
     */
    public void setScoreid(Integer scoreid) {
        this.scoreid = scoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_score.userid
     *
     * @return the value of exam_score.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_score.userid
     *
     * @param userid the value for exam_score.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_score.paperid
     *
     * @return the value of exam_score.paperid
     *
     * @mbggenerated
     */
    public Integer getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_score.paperid
     *
     * @param paperid the value for exam_score.paperid
     *
     * @mbggenerated
     */
    public void setPaperid(Integer paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_score.score
     *
     * @return the value of exam_score.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_score.score
     *
     * @param score the value for exam_score.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_score.rights
     *
     * @return the value of exam_score.rights
     *
     * @mbggenerated
     */
    public Integer getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_score.rights
     *
     * @param rights the value for exam_score.rights
     *
     * @mbggenerated
     */
    public void setRights(Integer rights) {
        this.rights = rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_score.errors
     *
     * @return the value of exam_score.errors
     *
     * @mbggenerated
     */
    public Integer getErrors() {
        return errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_score.errors
     *
     * @param errors the value for exam_score.errors
     *
     * @mbggenerated
     */
    public void setErrors(Integer errors) {
        this.errors = errors;
    }
}