package com.sz.zhiling.mapper;

import com.sz.zhiling.model.TRouse;
import com.sz.zhiling.model.TRouseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TRouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int countByExample(TRouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int deleteByExample(TRouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int insert(TRouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int insertSelective(TRouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    List<TRouse> selectByExample(TRouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    TRouse selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TRouse record, @Param("example") TRouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TRouse record, @Param("example") TRouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TRouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRouse record);
}