package com.sz.zhiling.mapper;

import com.sz.zhiling.model.ExamScore;
import com.sz.zhiling.model.ExamScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int countByExample(ExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int deleteByExample(ExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer scoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int insert(ExamScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int insertSelective(ExamScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    List<ExamScore> selectByExample(ExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    Integer add123(ExamScore examScore);

    ExamScore selectByPrimaryKey(Integer scoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamScore record, @Param("example") ExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamScore record, @Param("example") ExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamScore record);
}