package com.sz.zhiling.mapper;

import com.sz.zhiling.model.ExamItems;
import com.sz.zhiling.model.ExamItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int countByExample(ExamItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int deleteByExample(ExamItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int insert(ExamItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int insertSelective(ExamItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    List<ExamItems> selectByExample(ExamItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    ExamItems selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamItems record, @Param("example") ExamItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamItems record, @Param("example") ExamItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamItems record);
}