package com.sz.zhiling.mapper;

import com.sz.zhiling.model.ExamUser;
import com.sz.zhiling.model.ExamUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int countByExample(ExamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int deleteByExample(ExamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int insert(ExamUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int insertSelective(ExamUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    List<ExamUser> selectByExample(ExamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    ExamUser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamUser record, @Param("example") ExamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamUser record, @Param("example") ExamUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamUser record);
}