package com.sz.zhiling.mapper;

import com.sz.zhiling.model.ExamPaper;
import com.sz.zhiling.model.ExamPaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int countByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int deleteByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer paperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int insert(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int insertSelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    List<ExamPaper> selectByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    ExamPaper selectByPrimaryKey(Integer paperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamPaper record);
}