package com.sz.zhiling.mapper;

import com.sz.zhiling.model.ExamScoreDetail;
import com.sz.zhiling.model.ExamScoreDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamScoreDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int countByExample(ExamScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int deleteByExample(ExamScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int insert(ExamScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int insertSelective(ExamScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    List<ExamScoreDetail> selectByExample(ExamScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    ExamScoreDetail selectByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamScoreDetail record, @Param("example") ExamScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamScoreDetail record, @Param("example") ExamScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_score_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamScoreDetail record);
}