package com.sz.zhiling.mapper;

import com.sz.zhiling.model.Myanswer;
import com.sz.zhiling.model.MyanswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyanswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int countByExample(MyanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int deleteByExample(MyanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int insert(Myanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int insertSelective(Myanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    List<Myanswer> selectByExample(MyanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    Myanswer selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Myanswer record, @Param("example") MyanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Myanswer record, @Param("example") MyanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Myanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myanswer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Myanswer record);
}